version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metpol-app
    volumes:
      - ./app/data:/app/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_DB_PATH=/app/app/data/index
    ports:
      - "8000:8000"
    restart: unless-stopped
