services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - metpol-sqlite:/app/backend/server/data
      - metpol-db:/app/backend/data/prod/chroma_db
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - PRODUCTION=false
      - ENABLE_DB_DUMP=True
      - METROPOLE_DB_PATH=/app/backend/server/data/app.db
      - MAX_QUESTIONS_PER_DAY=50
      - MAX_QUESTIONS_PER_DAY_ADMIN=300

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend

  oauth2-proxy:
    image: bitnami/oauth2-proxy:latest
    command:
      - --upstream=http://sqlite-web:8081/
      - --http-address=0.0.0.0:4180
      - --cookie-secure=true
      - --cookie-samesite=lax
      - --set-xauthrequest=true
      - --pass-authorization-header=true
      - --pass-access-token=true
      - --skip-provider-button=true
      - --skip-auth-regex=^/oauth2/.*
      - --redirect-url=http://localhost:3000/oauth2/callback
    ports:
      - "4180:4180"
    environment:
      - OAUTH2_PROXY_PROVIDER=google
      - OAUTH2_PROXY_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_ALLOWED_EMAILS=${ADMIN_EMAILS}
    depends_on:
      - sqlite-web

  sqlite-web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: sqlite_web --read-only --host 0.0.0.0 --port 8081 /app/backend/server/data/app.db
    volumes:
      - metpol-sqlite:/app/backend/server/data
    expose:
      - "8081"
    depends_on:
      - backend

  nginx:
    image: nginx:1.25
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - oauth2-proxy
    restart: unless-stopped

volumes:
  metpol-sqlite:
  metpol-db:
