services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - metpol-sqlite:/data
      - metpol-db:/app/backend/data/prod/chroma_db
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - PRODUCTION=false
      - ENABLE_DB_DUMP=True
      - METROPOLE_DB_PATH=/data/app.db
      - MAX_QUESTIONS_PER_DAY=50
      - MAX_QUESTIONS_PER_DAY_ADMIN=300

  sqlite-web:
    image: coleifer/sqlite-web:latest
    command: sqlite_web --host 0.0.0.0 --port 8081 /data/app.db
    volumes:
      - metpol-sqlite:/data
    expose:
      - "8081"
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - sqlite-web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  metpol-sqlite:
  metpol-db:
