services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - metpol-sqlite:/app/backend/server/data
      - metpol-db:/app/backend/data/prod/chroma_db
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PRODUCTION=false
      - ENABLE_DB_DUMP=True
      - METROPOLE_DB_PATH=/app/backend/server/data/app.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend

volumes:
  metpol-sqlite:
  metpol-db:
