version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data/index
      - ./data/html:/app/data/html
      - ./data/processed:/app/data/processed
      - ./data/logs:/app/data/logs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_DB_PATH=/data/index
      - SECRET_KEY=${SECRET_KEY:-default_secret_key}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service (uncomment if you have a frontend)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - app
  #   restart: unless-stopped

volumes:
  chroma_data:
    driver: local
