version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metpol-backend
    volumes:
      - ./app/data:/app/app/data  # Persist embeddings/index
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_DB_PATH=/app/app/data/index
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: metpol-frontend
    environment:
      - BACKEND_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    restart: unless-stopped
