app = "metpol-ai-backend"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[env]
  CHROMA_DB_PATH = "/data/index"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "metpol_data"
  destination = "/data"

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/"
  timeout = "5s"
