services:
  - type: web
    name: metpol-ai
    runtime: docker
    repo: https://github.com/tlin23/METPOLE_AI
    branch: main
    plan: free
    dockerContext: . # root with your unified Dockerfile
    envVars:
      - key: CHROMA_DB_PATH
        value: /app/data/index
    disk:
      name: metpol-data
      mountPath: /app/data
      sizeGB: 1
