app = "metpol-ai"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PRODUCTION = "true"
  ENABLE_DB_DUMP = "True"
  MAX_QUESTIONS_PER_DAY = "50"
  MAX_QUESTIONS_PER_DAY_ADMIN = "300"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "1s"
